### PR TITLE
adds `yield` keyword

### PR DESCRIPTION
**Pull request by tur-nr**

### CODE REVIEW

**Comment by antoniobusrod** [comment]
great feature to have!

**Comment by hpurmann** [comment]
Hehe I just did the exact same locally and saw your PR afterwards :laughing:

**Comment by yukirin** [comment]
Nice PR, Will you add the `yield from` keyword?

**Comment by tur-nr** [comment]
Is `yield from` valid syntax in coffeescript?

**Comment by yukirin** [comment]
[yield from support](https://github.com/jashkenas/coffeescript/blob/4a7497b451b06b990a8dba3ad19371f28bb94824/test/generators.coffee#L77-L80 "yield from support")

**Comment by hpurmann** [comment]
@kchmck could you please merge that in? It's such an easy fix and until now, everybody using `yield` has to apply the same fix manually in their local repository :persevere:

**Comment by hpurmann** [comment]
Thanks a lot! :thumbsup:

**Comment by kchmck** [comment]
thanks for the ping

**Pull request merged**
